# Generated by Django 5.0.4 on 2024-04-20 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_alter_product_price_alter_shoppingcart_amount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShoppingCart',
            new_name='ShoppingItem',
        ),
    ]
